spring.application.name=ToyProject

# Oracle 데이터베이스 연결 설정
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xe
spring.datasource.username=C##TOY
spring.datasource.password=TOY
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA 설정
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# 포트번호 변경
server.port=8088